package qr

// Galois field GF(2^8) arithmetic as defined by ISO/IEC 18004.
//
// The field is generated by the primitive polynomial
//
//	x^8 + x^4 + x^3 + x^2 + 1  (0x11D)
//
// with primitive element alpha = 2. gfExp holds alpha^i and gfLog its
// inverse. gfExp is doubled in length so multiplication can index
// gfExp[log(a)+log(b)] without a modulo reduction.
var (
	gfExp [512]byte
	gfLog [256]byte
)

func init() {
	x := 1
	for i := 0; i < 255; i++ {
		gfExp[i] = byte(x)
		gfLog[byte(x)] = byte(i)
		x <<= 1
		if x&0x100 != 0 {
			x ^= 0x11d
		}
	}
	for i := 255; i < 512; i++ {
		gfExp[i] = gfExp[i-255]
	}
}

// gfMul multiplies two field elements.
func gfMul(a, b byte) byte {
	if a == 0 || b == 0 {
		return 0
	}
	return gfExp[int(gfLog[a])+int(gfLog[b])]
}
